---
output: html_document
---

```{r, include=FALSE}
library("knitr")
opts_chunk$set(tidy = FALSE)
```


```{r}
files_single <- list.files("data/seqs", pattern = "counts.txt$",
                           full.names = TRUE)
gene_anno <- read.table(files_single[1], header = TRUE, sep = "\t",
                        stringsAsFactors = FALSE)
gene_anno <- gene_anno[, c("Geneid", "Chr", "Start", "End", "Strand", "Length")]
gene_counts <- matrix(0, nrow = nrow(gene_anno), ncol = 4)
colnames(gene_counts) <- c("lane1_reads", "lane1_umi",
                           "lane2_reads", "lane2_umi")
```

```{r}
for (fname in files_single) {
  f <- read.table(fname, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
  stopifnot(f$Geneid == gene_anno$Geneid)
  if (grepl("lane1", fname)) {
    gene_counts[, "lane1_reads"] <- gene_counts[, "lane1_reads"] + f[, 7]
    gene_counts[, "lane1_umi"] <- gene_counts[, "lane1_umi"] + f[, 8]
  } else if (grepl("lane2", fname)) {
    gene_counts[, "lane2_reads"] <- gene_counts[, "lane2_reads"] + f[, 7]
    gene_counts[, "lane2_umi"] <- gene_counts[, "lane2_umi"] + f[, 8]
  } else {
    stop("Invalid filename")
  }
}
```

```{r}
plot(gene_counts[, "lane1_reads"], gene_counts[, "lane1_umi"])
plot(gene_counts[, "lane2_reads"], gene_counts[, "lane2_umi"])
plot(gene_counts[, "lane1_umi"], gene_counts[, "lane2_umi"])
plot(gene_counts[, "lane1_reads"], gene_counts[, "lane2_reads"])
```

