---
title: "Cell-to-cell variation analysis: summary"
author: "Joyce Hsiao"
date: 2016-07-06  
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options, include=FALSE}
source("chunk-options.R")

library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, eval = TRUE, 
               echo = TRUE)
```


## Setting up

```{r}
library(EBImage)
```


## Objective

Try out the R package `EBImage` on the FUCCI images. 

Reference: https://www.r-bloggers.com/r-image-analysis-using-ebimage/

## Importing data

```{r}
file_name <- "/Users/joycehsiao/Dropbox/GitHub/singleCellSeq/data/fucci/18511-19101-01.tif"

Image <- readImage(file_name)
display(Image)
```

## Get the image properties

```{r}
print(Image)
```

Adjust brightness

```{r}
# brighter
Image1 <- Image + .2
# darker
Image2 <- Image - .2
display(Image1)
display(Image2)
```

Adjusting contrast

```{r}
Image3 <- Image*.5 # low contrast
Image4 <- Image*2 # high contrast
display(Image3)
display(Image4)
```






## Session information

```{r}
sessionInfo()
```

