---
title: "Generate gene symbols"
author: "Joyce Hsiao"
date: 2016-07-01
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options, include=FALSE}
source("chunk-options.R")

library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, eval = TRUE, 
               echo = TRUE)
```


## Objective

Get gene symbols for the final data set and save them in a text file for annotation references.

## Set up

```{r, message=FALSE, warning=FALSE}
library("data.table")
library("dplyr")
library("limma")
library("edgeR")
library("ggplot2")
library("grid")
theme_set(theme_bw(base_size = 12))
source("functions.R")
```

Input annotation of QC-filtered data.

```{r}
anno_filter <- read.table("../data/annotation-filter.txt", 
                          header = TRUE,
                          stringsAsFactors = FALSE)
```


Import endogeneous genes in the final file.

```{r}
molecules_final <- read.table("../data/molecules-final.txt", 
                             header = TRUE, 
                             stringsAsFactors = FALSE)
```


## Generate Gene IDs


```{r}
if(file.exists("../data/gene-info.txt")) {
   gene_info <- read.table(file = "../data/gene-info.txt", sep = "\t",
                          header = TRUE, stringsAsFactors = FALSE, quote = "")
   head(gene_info)
} else {
library("biomaRt")
  ensembl <- useMart(host = "grch37.ensembl.org",
                     biomart = "ENSEMBL_MART_ENSEMBL",
                     dataset = "hsapiens_gene_ensembl")

  gene_info <- getBM(attributes = c("ensembl_gene_id", 
                               "chromosome_name",
                               "external_gene_name", 
                               "transcript_count",
                               "description"),
                      filters = "ensembl_gene_id",
                      values = rownames(molecules_final),
                      mart = ensembl)
  write.table(gene_info, row.names = FALSE,
              file = "../data/gene-info.txt", quote = FALSE, sep = "\t") 

  write.table(gene_info$external_gene_name, row.names = FALSE, col.names = F,
            file = "../data/gene-info-symbol-only.txt", quote = FALSE, sep = "\t") 
}
```


## Runtime

```{r}
t1 <- Sys.time()
library("biomaRt")
  ensembl <- useMart(host = "grch37.ensembl.org",
                     biomart = "ENSEMBL_MART_ENSEMBL",
                     dataset = "hsapiens_gene_ensembl")

  gene_info <- getBM(attributes = c("ensembl_gene_id", 
                               "chromosome_name",
                               "external_gene_name", 
                               "transcript_count",
                               "description"),
                      filters = "ensembl_gene_id",
                      values = rownames(molecules_final),
                      mart = ensembl)
t2 <- Sys.time()
```

Takes `r t2 - t1` to processs `r NROW(molecules_final)`.


## Session information

```{r info}
sessionInfo()
```
