---
title: "License"
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

## Code

The code is licensed under the [GPLv3][code-license].
We use multiple [Bioconductor][bioc] packages which are GPL'd.

[bioc]: https://www.bioconductor.org/about

## Site

Currently our results are licensed under the [Creative Commons Attribution-NoDerivatives 4.0 International License][site-license].
This means you are free to include content from this site in your presentation, blog, or social media posts, as long you cite us.
The "no derivatives" clause means you cannot modify the results and distribute them.
Basically, we want to be the first to publish the analysis of this data, so as long as you don't analyze the data yourself and include the results in a publication, there is no problem.
Once we publish, we'll remove "no derivatives" clause to encourage re-use.

## How to cite us

If you use a figure or text excerpt from this site, please cite us by including the following (or something similar):

> From the Gilad Lab: http://jdblischak.github.io/singleCellSeq/analysis

[code-license]: https://www.gnu.org/licenses/gpl-3.0.txt
[site-license]: https://creativecommons.org/licenses/by-nd/4.0/
