---
title: "Over-expressed genes"
author: "PoYuan Tung"
date: 2015-10-14
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options, include=FALSE}
source("chunk-options.R")
```

```{r}
molecules <- read.table("../data/molecules.txt", header = TRUE,
                   stringsAsFactors = FALSE)

rownames(molecules)[rowMeans(molecules) > 1024]

## overexpressed genes
overexpressed_rows <- apply(molecules, 1, function(x) any(x >= 1024))
overexpressed_genes <- rownames(molecules_filter)[overexpressed_rows]
overexpressed_genes_exp <- molecules_filter[overexpressed_genes,]

## cells with overexpressed genes
overexpressed_col <- apply(molecules, 2, function(x) any(x >= 1024))
overexpressed_cell <- colnames(molecules)[overexpressed_col]

## outlier cells 
outlier_cells <- c("NA19098.r3.B04", "NA19098.r3.B11", "NA19101.r1.B10", "NA19101.r2.D07", "NA19101.r2.F06", "NA19101.r3.C07", "NA19101.r3.D08", "NA19101.r3.D10", "NA19101.r3.F05", "NA19101.r3.F10", "NA19239.r2.A12", "NA19239.r2.B07")

```
