---
title: "Meeting with Yoav"
author: "PoYuan Tung"
date: 2015-04-28
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options, include=FALSE}
source("chunk-options.R")
```


__Our super exciting research plan for single cell RNA-seq__ 

# Technical aspects

1. single cell vs. bulk
* the read depth required for each cell
* the number of cells to represent bulk

2. reads vs. molecules
* bias due to: 
  + (a) expression level  
  + (b) GC content 
  + (c) UMI sequence 
  + (d) distribution

3. model for the technical noise (working with Joyce)

# Biological aspects

1. identification of noisy genes in iPSCs 

2. difference of noise levels (of noisy genes) between individuals

3. heterogeneity of iPSC compared to LCLs 

# LCL data 

1. comparison of Tn5 transposasw (in-house vs. Epicentre)

2. modeling of the single cell RNA-seq using the ERCC

# Additional (that we didn’t talk about)

1. alternative start sides 

2. allele-specific expression

