---
title: "Subsampling replicates for supplementary figure"
date: 2016-10-27
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

```{r chunk-options, include=FALSE}
source("chunk-options.R")
opts_chunk$set(cache = FALSE)
```

The reviewers asked to see the results of the subsampling for each batch.
The data was created with [subsample-pipeline-rep.py](https://github.com/jdblischak/singleCellSeq/blob/master/code/subsample-pipeline-rep.py).
The analysis below was modified from the [original analysis](subsample-final.html) for Figure 2.

## Input

```{r packages, message=FALSE, cache=FALSE}
library("dplyr")
library("tidyr")
library("ggplot2")
library("cowplot")
theme_set(theme_bw(base_size = 12))
theme_update(panel.grid.minor.x = element_blank(),
             panel.grid.minor.y = element_blank(),
             panel.grid.major.x = element_blank(),
             panel.grid.major.y = element_blank(),
             legend.key = element_blank())
```

```{r input-data}
d <- read.table("../data/subsampling-results-rep.txt",
                header = TRUE, sep = "\t", stringsAsFactors = FALSE)
str(d)
```

```{r group}
d_grouped <- d %>%
  group_by(type, depth, gene_subset, subsampled_cells,
           individual, replicate, potential_cells, available_cells,
           lower_q, upper_q, available_ensg, used_ensg,
           available_ercc, used_ercc) %>%
  summarize(mean_detected = mean(detected_ensg),
            sem_detected = sd(detected_ensg) / sqrt(length(detected_ensg)),
            mean_bulk = mean(pearson_ensg),
            sem_bulk = sd(pearson_ensg) / sqrt(length(pearson_ensg)),
            mean_var = mean(var_pearson),
            sem_var = sd(var_pearson) / sqrt(length(var_pearson)))
```

```{r filter}
d_filter <- d_grouped %>% filter(type == "molecules",
                                 gene_subset %in% c("lower")) %>%
  mutate(batch = paste(individual, replicate, sep = "-"))
d_filter$depth2 <- factor(d_filter$depth,
                          labels = format(unique(d_filter$depth), big.mark = ",",
                                          scientifc = FALSE, trim = TRUE))
```

## Figures

```{r plot-base}
plot_base <- ggplot(d_filter,
                 aes(x = subsampled_cells,
                     color = individual, shape = replicate)) +
  geom_point(alpha = 0.5) +
  geom_line(alpha = 0.5) +
  facet_wrap(~depth2, ncol = 1) +
  scale_x_continuous(breaks = unique(d_filter$subsampled_cells)) +
  scale_color_discrete(name = "Individual") +
  scale_shape(name = "Replicate") +
  theme(legend.position = "none", axis.text.x = element_text(size = rel(0.75)))
```

```{r plot-bulk}
plot_bulk <- plot_base %+% aes(y = mean_bulk) +
  theme(legend.position = c(0.75, 0.875),
        legend.key.size = grid::unit(0.25, "in")) +
  guides(shape = FALSE) +
  labs(x = "Number of subsampled cells",
       y = "Pearson's r",
       title = "Correlation with bulk")
plot_bulk
```

```{r plot-detected}
plot_detected <- plot_base %+% aes(y = mean_detected) +
  geom_errorbar(aes(ymin = mean_detected - sem_detected,
                    ymax = mean_detected + sem_detected),
                width = 1, alpha = 0.5) +
  theme(legend.position = c(0.75, 0.875),
        legend.key.size = grid::unit(0.25, "in")) +
  guides(color = FALSE) +
  labs(x = "Number of subsampled cells",
       y = "Number of genes detected",
       title = "Genes detected")
plot_detected
```

```{r plot-var}
plot_var <- plot_base %+% aes(y = mean_var) +
  geom_errorbar(aes(ymin = mean_var - sem_var,
                    ymax = mean_var + sem_var),
                width = 1, alpha = 0.5) +
  labs(x = "Number of subsampled cells",
       y = "Pearson's r",
       title = "Cell-to-cell variance")
plot_var
```

```{r plot-final, fig.width=12, fig.height=16}
plot_final <- plot_grid(plot_bulk, plot_detected, plot_var,
                        ncol = 3, labels = letters[1:3])
plot_final
tiff("../paper/figure/fig-subsample-rep.tiff",
     width = 6 * 1.5, height = 8 * 1.5,
     units = "in", res = 300, compression = "zip")
plot_final
dev.off()
# Uncompressed version for Word
tiff("../paper/figure/fig-subsample-rep-uncompressed.tiff",
     width = 6 * 1.5, height = 8 * 1.5,
     units = "in", res = 300, compression = "none")
plot_final
dev.off()
```

## Session information

```{r info}
sessionInfo()
```
